[package]
name = "tokio-openssl"
version = "0.1.1"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/alexcrichton/tokio-openssl"
homepage = "https://github.com/alexcrichton/tokio-openssl"
documentation = "https://docs.rs/tokio-openssl"
description = """
An implementation of SSL streams for Tokio backed by OpenSSL
"""

[dependencies]
openssl = "0.9"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
